services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.9
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true' # dev only
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: ''
      DEFAULT_VECTORIZER_MODULE: '' # no built-in vectorizer we'll use the external
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - '8080:8080'
      - '50051:50051'
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
